=== gautierenaud/ProjetMDSI/BaseDonnees/BD/bd.xsd
<?xml version ="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:complexType name="type-personne"><!--peut etre ID en attribut..  -->
		<xsd:sequence>
			<xsd:element name="Nom" type="xsd:string" minOccurs="1"/>
			<xsd:element name="Prenom" type= "xsd:string" minOccurs="1"/>
			<xsd:element name="Anniv" type ="xsd:date" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="ID" type="xsd:ID" />
	</xsd:complexType>
	
	<xsd:complexType name="type-matiere">
		<xsd:sequence>
			<xsd:element name="Nom" type="xsd:string" minOccurs="1"/>
			<xsd:element name="Code" type="xsd:string" minOccurs="1"/>
			<xsd:element name="Credit" type="xsd:int" minOccurs="1"/>
			<xsd:element name="UFID">
				<xsd:complexType>
				<xsd:attribute name="ufID" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="ID" type="xsd:ID"/>
	</xsd:complexType>
	
	<xsd:simpleType name="noteInt">
		<xsd:restriction base="xsd:int">	
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="20" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:element name="Enseignants">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Enseignant" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="Etudiants">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Etudiant" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="ListCursus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Cursus" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:simpleType name="CursusType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Info"/>
			<xsd:enumeration value="Math"/>
			<xsd:enumeration value="Civil"/>
			<xsd:enumeration value="Meca"/>
			<xsd:enumeration value="BioC"/>
			<xsd:enumeration value="ProC"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:element name="Cursus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="UF" maxOccurs="6"/>
			</xsd:sequence>
			<xsd:attribute name="CursusName" type="CursusType">
				
			</xsd:attribute>
		</xsd:complexType>
		<xsd:key name="CursusKey">
			<xsd:selector xpath="ListCursus/Cursus"/>
			<xsd:field xpath="@CursusName"/>
		</xsd:key>
	</xsd:element>
	
	<xsd:element name="UF">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="MatID" minOccurs="1" maxOccurs="3"/>
			</xsd:sequence>
			<xsd:attribute name="ID" type="xsd:string"/>
		</xsd:complexType>
		<xsd:keyref name="UFmatiereRef" refer="MatiereKey">
			<xsd:selector xpath="Matieres/Matiere" />
			<xsd:field xpath="MatID/@MatiereID" />
		</xsd:keyref>
		<xsd:key name="UFKey">
			<xsd:selector xpath="ListCursus/Cursus/UF"/>
			<xsd:field xpath="@ID" />
		</xsd:key>
	</xsd:element>
	
	<xsd:element name="Matieres">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Matiere" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="Matiere" type="type-matiere">
		<xsd:keyref name="MatiereUFRef" refer="UFKey">
			<xsd:selector xpath="ListCursus/Cursus/UF" />
			<xsd:field xpath="UFID/@ufID" />
		</xsd:keyref>
		<xsd:key name="MatiereKey">
			<xsd:selector xpath="Matieres/Matiere"/>
			<xsd:field xpath="@ID" />	
		</xsd:key>
	</xsd:element>
	
	<xsd:element name="Etudiant">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Personne" type="type-personne" />
				<xsd:element name="Matieres">  
					<xsd:complexType>
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="MatieresParAnnee" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="MatID" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Note" type="noteInt" minOccurs="0" maxOccurs="unbounded"/>
												</xsd:sequence>
												<xsd:attribute name="MatiereID" type="xsd:string"/>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="Annee" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
					<xsd:keyref name="EtudMatiereRef" refer="MatiereKey">
						<xsd:selector xpath="Matieres/Matiere" />
						<xsd:field xpath="MatID/@MatiereID" />
					</xsd:keyref>
				</xsd:element>
				<xsd:element name="AnneeActuelle" type="xsd:int"/>
				<xsd:element name="Cursus">
					<xsd:complexType>
						<xsd:attribute name="CursusName" type="CursusType" />
					</xsd:complexType>
						<xsd:keyref name="CursusRef" refer="CursusKey">
							<xsd:selector xpath="ListCursus/Cursus" />
							<xsd:field xpath="Cursus/@CursusName" />
						</xsd:keyref>
				</xsd:element>
				<xsd:element name="Groupe" type="xsd:string"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="Enseignant">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Personne" type="type-personne" />
				<xsd:element name="MatID" minOccurs="0" maxOccurs="unbounded" >
					<xsd:complexType>
						<xsd:attribute name="MatiereID" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Grade" type="xsd:string"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:keyref name="EnseignMatiereRef" refer="MatiereKey">
			<xsd:selector xpath="Matieres/Matiere" />
			<xsd:field xpath="MatID/@MatiereID" />
		</xsd:keyref>
	</xsd:element>
</xsd:schema>

=== gautierenaud/ProjetMDSI/BaseDonnees/BD/Enseignant.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Enseignants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bd.xsd">
	<Enseignant>
		<Personne ID="lb54">
			<Nom>Le Botlan</Nom>
			<Prenom>Didier</Prenom>
			<Anniv>1998-08-08</Anniv>
		</Personne>
		<MatID MatiereID="p42"/>
		<Grade>assistant</Grade>
	</Enseignant>
	<Enseignant>
		<Personne ID="m2005">
			<Nom>Tomtom</Nom>
			<Prenom>Motmot</Prenom>
			<Anniv>1998-10-08</Anniv>
		</Personne>
		<MatID MatiereID="p42"/>
		<MatID MatiereID="h57"/>
		<MatID MatiereID="u25"/>
		<Grade>doctorant</Grade>
	</Enseignant>
	<Enseignant>
		<Personne ID="fl98">
			<Nom>La Botlanne</Nom>
			<Prenom>Didiette</Prenom>
			<Anniv>1800-10-18</Anniv>
		</Personne>
		<MatID MatiereID="o02"/>
		<Grade>fossile</Grade>
	</Enseignant>
	<Enseignant>
		<Personne ID="tgv2596">
			<Nom>Bergerac</Nom>
			<Prenom>Cyrano</Prenom>
			<Anniv>1897-08-08</Anniv>
		</Personne>
		<MatID MatiereID="fr2"/>
		<Grade>grand ma√Ætre</Grade>
	</Enseignant>
</Enseignants>

=== gautierenaud/ProjetMDSI/BaseDonnees/Etudiant.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Etudiants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bd.xsd">
	<Etudiant>
		<Personne ID="lb54">
			<Nom>Le Botlan</Nom>
			<Prenom>Didier</Prenom>
			<Anniv>1998-08-08</Anniv>
		</Personne>
		<Matieres>
			<MatID MatiereID="p42">
				<Note>10</Note>
			</MatID>
		</Matieres>
		<Annee>45</Annee>
		<Cursus>Info</Cursus>
		<Groupe>TDA</Groupe>
	</Etudiant>
</Etudiants>

=== gautierenaud/ProjetMDSI/BaseDonnees/BD/Etudiant.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Etudiants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bd.xsd">
	<Etudiant>
		<Personne ID="lb54">
			<Nom>Le Botlan</Nom>
			<Prenom>Didier</Prenom>
			<Anniv>1998-08-08</Anniv>
		</Personne>
		<Matieres>
			<MatID MatiereID="p42">
				<Note>10</Note>
			</MatID>
		</Matieres>
		<Annee>45</Annee>
		<Cursus>Info</Cursus>
		<Groupe>TDA</Groupe>
	</Etudiant>
	<Etudiant>
	<Personne ID="lb55">
		<Nom>Bastien</Nom>
		<Prenom>Delegue</Prenom>
		<Anniv>1998-01-08</Anniv>
	</Personne>
	<Matieres>
		<MatID MatiereID="p42">
			<Note>30</Note>
		</MatID>
	</Matieres>
	<Annee>44</Annee>
	<Cursus>Info</Cursus>
	<Groupe>TDA</Groupe>
	</Etudiant>
	<Etudiant>
	<Personne ID="lb56">
		<Nom>Truc</Nom>
		<Prenom>Chose</Prenom>
		<Anniv>1988-10-08</Anniv>
	</Personne>
	<Matieres>
		<MatID MatiereID="p97">
			<Note>8</Note>
			<Note>12</Note>
		</MatID>
	</Matieres>
	<Annee>45</Annee>
	<Cursus>GC</Cursus>
	<Groupe>TDA</Groupe>
	</Etudiant>
</Etudiants>

=== gautierenaud/ProjetMDSI/BaseDonnees/BD/Matiere.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Matieres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bd.xsd">
	<Matiere ID="p42">
		<Nom>Info Mat</Nom>
		<Code>toto</Code>
		<Credit>0</Credit>
		<UFID ufID="uf50"/>
	</Matiere>
	<Matiere ID="f42">
		<Nom>Info Mat</Nom>
		<Code>toto</Code>
		<Credit>0</Credit>
		<UFID ufID="ufprout"/>
	</Matiere>
</Matieres>
